### ISSUE TITLE
src/client.cc:1:10: fatal error: 'sstream' file not found

### ISSUE THREAD

**Issue by yh392261226** [rogual/homebrew-neovim-dot-app#18]
brew install rogual/neovim-dot-app/neovim-dot-app                                                                                                                             2.13   2.97G   98% 🔋  10:22:10
Updating Homebrew...
==> Installing neovim-dot-app from rogual/neovim-dot-app
==> Downloading https://github.com/rogual/neovim-dot-app/archive/0.1.5.tar.gz
Already downloaded: /Users/json/Library/Caches/Homebrew/neovim-dot-app-0.1.5.tar.gz
==> make NVIM=/usr/local/opt/neovim/bin/nvim
Last 15 lines from /Users/json/Library/Logs/Homebrew/neovim-dot-app/01.make:
2016-11-17 10:22:21 +0800

make
NVIM=/usr/local/opt/neovim/bin/nvim

VIM=/usr/local/Cellar/neovim/HEAD-5e241b5/share/nvim NVIM=/usr/local/opt/neovim/bin/nvim scons -Q
Install file: "res/Info.plist" as "build/Neovim.app/Contents/Info.plist"
clang++ -o build/client.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -mmacosx-version-min=10.9 -I/usr/local/Cellar/msgpack/2.0.0/include -Ibuild -Isrc src/client.cc
src/client.cc:1:10: fatal error: 'sstream' file not found
#include <sstream>
         ^
1 error generated.
scons: *** [build/client.o] Error 1
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/rogual/homebrew-neovim-dot-app/issues

**Comment by rogual** [comment]
Closing in favour of https://github.com/rogual/neovim-dot-app/issues/306
