### ISSUE TITLE
breaks with non-standard prefix

### ISSUE THREAD

**Issue by glyph** [rogual/homebrew-neovim-dot-app#7]
If Homebrew is not installed in `/usr/local`, the build fails with: 

```
clang++ -o build/Neovim.app/Contents/MacOS/Neovim build/client.o build/process.o build/rpc.o build/vim.o build/vimutils.o build/app.o build/font.o build/graphics.o build/input.o build/keys.o build/main.o build/menu.o build/redraw.o build/view.o build/window.o -lc++ -lmsgpack -framework Cocoa -framework Carbon
ld: library not found for -lmsgpack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/Neovim.app/Contents/MacOS/Neovim] Error 1
make: *** [all] Error 2
```

**Comment by rogual** [comment]
Wherever Homebrew installs libraries to, that path needs to be in your linker search path. The default, /usr/local, is added to the search path when you install the Xcode CLI tools. I don't know if there's a Homebrew tool to do the same for non-default locations, but that's what you need to do.

**Comment by kiliankoe** [comment]
My hombrew install is in `/usr/local` and I'm also running into this issue 😕

**Comment by rogual** [comment]
@kiliankoe Did you see the bit in neovim-dot-app's README addressing this? The steps there usually fix this issue.

**Comment by kiliankoe** [comment]
I wouldn't have guessed `xcode-select --install` to solve this issue, but apparently it did. Thanks! And sorry for not checking out the readme more carefully 🙃

**Comment by rogual** [comment]
Thanks to the recent contribution of pkgconfig support, I suspect this issue may have disappeared once and for all. Tentatively closing this.
